### ISSUE TITLE
Problems in running the code

### ISSUE THREAD

**Issue by joefresna** [ludericv/information-market#1]
By following the documentation, I get the following issue:

```
$ cd src/

$ ls
controllers      data_analysis.py helpers          info_market.py   model

$ python info_market.py ../config/config.txt
Traceback (most recent call last):
  File "/Users/joefresna/information-market/src/info_market.py", line 1, in <module>
    from controllers.main_controller import MainController, Configuration
  File "/Users/joefresna/information-market/src/controllers/main_controller.py", line 3, in <module>
    from src.model.environment import Environment
ModuleNotFoundError: No module named 'src'
```

I solved it by running it from the parent folder:

```
$ cd ..

$ python src/info_market.py config/config.txt
```

**Comment by ludericv** [comment]
there was indeed a problem with the imports, this issue should be fixed now
